title: "CSCI 344: Spring 2025"
subtitle: "Advanced Web Technology"
email: vanwars@unca.edu
baseurl: "/spring2025"
term_start_date: "2025-01-13"
term_end_date: "2025-05-09"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

timezone: "America/New_York"
# Build settings
markdown: kramdown
# kramdown:
#   syntax_highlighter_opts:
#     block:
#       line_numbers: true
theme: minima
plugins:
  - jekyll-feed
exclude: 
  - course-files/programming-bootcamp*
  - course-files/*/*/solutions/node_modules*
  - course-files/*/*/node_modules*
  - course-files/*/*/answers/node_modules*
  - course-files/*/*/solutions/env*
  - course-files/*/*/env*
  - course-files/*/*/answers/env*
  - _lectures/draft*
  - _assignments/draft*
  - _quizzes/draft*
  - course-files/administrative
  - course-files/build
  - course-files/exams
  - course-files/*/drafts
collections:
  assignments:
    output: true
    sort_by: ordering
    permalink: /assignments/:name
  lectures:
    output: true
    sort_by: lecture_date
    permalink: /lectures/:name
  topics:
    output: true
    permalink: /topics/:name
  activities:
    output: true
    permalink: /activities/:name
  quizzes:
    output: true
    sort_by: lecture_date
    permalink: /quizzes/:name
  resources:
    output: true
    permalink: /resources/:name/


collections_dir: pages

sass:
  style: compact
  sass_dir: _sass

deadline_reminder: true


